distributable:
  url: https://github.com/quickwit-oss/quickwit/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

provides:
  - bin/quickwit

versions:
  github: quickwit-oss/quickwit
  strip: /v/

dependencies:
  # This is a runtime dep since they use protos at runtime:
  # https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-proto/protos/quickwit/search.proto
  protobuf.dev: "*"

build:
  working-directory: quickwit/quickwit-cli
  dependencies:
    rust-lang.org: ">=1.65"
    rust-lang.org/cargo: "*"
  script: cargo install --locked --path . --root {{prefix}}

test:
  script:
    - quickwit --help
    # TODO: The version command prints out:
    # Quickwit 0.6.3-nightly (4a36f63 2023-12-03T14:01:02Z)
    # Where is "0.6.3-nightly" coming from??? Why isn't it 0.6.4?
    - quickwit --version
    # - test "$(quickwit --version)" = "quickwit {{version}}"
