distributable:
  url: https://github.com/radicle-dev/heartwood/archive/1af9480b088c3eec800040a1bdcd09941a31bcf3.tar.gz
  strip-components: 1

versions:
  - 2023.11.30

dependencies:
  openssl.org: ^1.1.1

build:
  working-directory: radicle-cli
  dependencies:
    rust-lang.org/cargo: ^0
    cmake.org: ^3
    freedesktop.org/pkg-config: ^0.29
  script: |
    cargo install --path . --root {{prefix}}

test: rad --help

provides:
  - bin/rad
  - bin/git-remote-rad
  - bin/rad-account
  - bin/rad-auth
  - bin/rad-checkout
  - bin/rad-clone
  - bin/rad-edit
  - bin/rad-ens
  - bin/rad-gov
  - bin/rad-help
  - bin/rad-init
  - bin/rad-inspect
  - bin/rad-issue
  - bin/rad-ls
  - bin/rad-merge
  - bin/rad-patch
  - bin/rad-path
  - bin/rad-pull
  - bin/rad-push
  - bin/rad-remote
  - bin/rad-reward
  - bin/rad-rm
  - bin/rad-self
  - bin/rad-sync
  - bin/rad-track
  - bin/rad-untrack
