distributable:
  url: https://github.com/garden-io/garden/archive/refs/tags/{{version}}.tar.gz
  strip-components: 1

versions:
  github: garden-io/garden

provides:
  - bin/garden

build:
  dependencies:
    npmjs.com: "*"
  script: |
    npm install
    npm run build
    ls -la cli/bin

test: garden --version | grep {{version}}
