distributable:
  url: https://github.com/coqui-ai/TTS/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: coqui-ai/TTS/releases
  strip: /^v/

# FIXME: inherited from taku910.github.io/mecab
# versions from 0.16.0 don't require mecab, now.
platforms:
  - darwin
  - linux/x86-64

provides:
  - bin/tts
  - bin/tts-server
  - bin/ttx

dependencies:
  python.org: '>=3.7 <3.11'
  taku910.github.io/mecab: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    pip.pypa.io: '*'
    git-scm.org: '*'
  script:
    # Supposedly, requirement on MeCab was removed, but the test complains of it missing
    - run: cat requirements.ja.txt >> requirements.txt
      if: =0.16.0
    - python-venv.py {{prefix}}/bin/tts --requirements-txt
    - run: |
        ln -sf tts tts-server
        ln -sf tts ttx
      working-directory: ${{prefix}}/bin

test: tts -h
